### ISSUE TITLE
References to complementary extensions

### ISSUE THREAD

**Issue by grahamperrin** [brettz9/jump-to-anchor#19]
https://github.com/brettz9/jump-to-anchor/commit/b0495e22c391dfed8555362f9b589feb6c62fb7c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R28

<https://addons.mozilla.org/addon/show-anchors-2/> is no longer available. 

For what it's worth, two alternative complementary extensions are mentioned by me at <https://forums.FreeBSD.org/threads/81963/post-530203>

----

### Side note

Non-localised AMO URLs, for example <https://addons.mozilla.org/addon/jump-to-anchor/>, will be more useful to readers whose preferred language is not English.

**Comment by brettz9** [comment]
Thanks for the report!

**Comment by grahamperrin** [comment]
Thanks for the fix!
