### ISSUE TITLE
Context menu item not appearing in private browsing mode

### ISSUE THREAD

**Issue by uusijani** [brettz9/jump-to-anchor#2]
I'm using Firefox 41.0 (in Ubuntu 14.04). Steps to reproduce:
1. Go to Firefox privacy settings, set "Remember history" (allow FF to restart if needed)
2. Install jump to anchor
3. Verify it works (context menu has "Jump to anchor")
4. Go to Firefox privacy settings, set "Never remember history" and allow FF to restart
5. Open context menu

What happens:
"Jump to anchor" is missing from the context menu.

**Comment by brettz9** [comment]
Thanks for the report--I see that private browsing support is opt-in, so I can look into adding that support. The only problem is whether the AMO reviewers will think that jumping to an anchor violates privacy--since there are now APIs to listen on hash (i.e., anchor) changes...

**Comment by uusijani** [comment]
All right, thanks for looking into this — whatever the outcome.

**Comment by brettz9** [comment]
I've just submitted a new version to AMO which supports the private browsing. You can await for any approval or go to "Versions" and install version 0.4.0

If you wouldn't mind giving the add-on a review (at https://addons.mozilla.org/en-US/firefox/addon/jump-to-anchor/ ), I'd appreciate it too...

I'm closing the issue for now, as it should be working, but you are welcome to keep commenting on this topic here.

**Comment by uusijani** [comment]
Just tested it and I can confirm that it works. Thanks a lot! I'll post a review on AMO right after this.

**Comment by brettz9** [comment]
Great to hear it's working for you. And thank you for your kind words on the review...
