### ISSUE TITLE
USe GitHub release tags

### ISSUE THREAD

**Issue by rugk** [brettz9/jump-to-anchor#3]
Could you please use [GitHub release tags](https://github.com/brettz9/jump-to-anchor/releases) when publishing a new release?
That's just the recommend way to do it and makes it possible to find past (or the most current) release much quicker.

**Comment by brettz9** [comment]
I'm a bit forgetful, so I can't promise anything, but will try to keep it in mind. I've added one for the latest, 0.4.0.
