### ISSUE TITLE
Menu Wizard: Icon not hideable

### ISSUE THREAD

**Issue by rugk** [brettz9/jump-to-anchor#4]
With [Menu Wizard](https://addons.mozilla.org/de/firefox/addon/s3menu-wizard/) I cannot hide the context menu entry:
![nothidable](https://cloud.githubusercontent.com/assets/11966684/10910468/d987b860-823f-11e5-9b81-bad4959de744.png)

**Comment by brettz9** [comment]
Menu Wizard relies on context menu items having an ID. My addon is using the recommended approach for building add-ons, the Firefox SDK, which currently does not allow adding an ID. Mozilla is open to this, however (as per https://bugzilla.mozilla.org/show_bug.cgi?id=956461 ), but someone will need to provide a patch/PR for Mozilla to fix it first.

**Comment by rugk** [comment]
Good to know. Thanks.
Hope sometimes in the future this can be fixed. Currently it is not such a bad usability issue as it does only affect some people, so this is not urgent.

**Comment by rugk** [comment]
Remember: Mozilla takes patches for this feature, so if you can implement it this would solve this problem.

**Comment by rugk** [comment]
FYI I also [left a comment](https://addons.mozilla.org/de/firefox/addon/s3menu-wizard/reviews/771438/) for the creator of Menu Wizard.

**Comment by rugk** [comment]
In Menu Wizard 4.01 the developer of Menu Wizard added a workaround. You can now activate this option in the settings:
![menuwizardsetid](https://cloud.githubusercontent.com/assets/11966684/12376672/b7a68158-bd00-11e5-8400-9bd46846ea38.PNG)

With this option activated you can hide the menu icon again.

**Comment by brettz9** [comment]
Awesome, thanks for the info!
