### ISSUE TITLE
Does not work with local files

### ISSUE THREAD

**Issue by rugk** [brettz9/jump-to-anchor#5]
This addon does not seem to work with local opened html files.

I sued [this file](https://gist.github.com/rugk/e1f40bdf8d773665228a) for testing and opened it locally (`file:///`) and it did not work.

**Comment by brettz9** [comment]
I've added support for the file protocol in version 0.5.0 (now awaiting review on AMO).

**Comment by rugk** [comment]
Ah okay. Thanks for the information.

**Comment by rugk** [comment]
BTW do not forget the GitHub release tags... :smile:

**Comment by brettz9** [comment]
Yes, you see how badly I need reminders. :) Done...

**Comment by brettz9** [comment]
And AMO has approved, btw...

**Comment by rugk** [comment]
Nice :smile: 

Just tried it and I can confirm this is fixed. Now it works. :smile:
