### ISSUE TITLE
Convert to WebExtensions

### ISSUE THREAD

**Issue by jomo** [brettz9/jump-to-anchor#7]
Firefox is [deprecating the old extensions](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing) and will only support WebExtensions in the near future. This plugin doesn't deal with any Firefox internals, it's all JavaScript, so I don't think it's going to be a lot of work.

**Comment by rugk** [comment]
Firefox 57 will be released soon…, so please… 😃

**Comment by yfdyh000** [comment]
A cookie: https://greasyfork.org/scripts/34811-jump-to-anchor

**Comment by yfdyh000** [comment]
I have tried to port it to WebExtensions but encountered some difficulties, and just think of the WebExtensions does not allow an extension to add more than one top-level contextMenus.

**Comment by jomo** [comment]
Made a PR in #8
